### PR TITLE
64 bit compatibility

### PR DESCRIPTION
**Pull request by nxdefiant**
Convert all return values of string::find from int to size_t

### CODE REVIEW

**Comment by freemangordon** [comment]
Ack. Lets @MerlijnWajer have a look at it too. Does this fix some particular issue?

**Comment by nxdefiant** [comment]
Yes, for example comparing the output of string::find to string::npos will always fail for int because of the different types.
With the changes I was able to import an *.ics-file with `qalendar --background` and `dbus-send --session --type=method_call --print-reply --dest=com.nokia.calendar /com/nokia/calendar com.nokia.calendar.mime_open string:"file:///path/to/file.ics"`

**Comment by IMbackK** [comment]
related: https://github.com/maemo-leste/bugtracker/issues/471

**Comment by IMbackK** [comment]
also i agree with the linked commit that string::size_type is the correct type here, not size_t, altho ofc currently these are the same.

**Comment by MerlijnWajer** [comment]
Looks good to me!

**Pull request merged**
